// examples/hmr-solid/routes/index.tsx
import type { LoaderArgs, LoaderData } from "@nifrajs/client"
import type { backend } from "../backend"
import { Counter } from "../components/Counter"

export const meta = {
  title: "nifra - HMR (Solid)",
  meta: [{ name: "description", content: "True HMR via @nifrajs/web/vite" }],
}

// Proves SSR still runs under the Vite dev server: this value is server-rendered into the document.
export async function loader({ api }: LoaderArgs<typeof backend>) {
  const res = await api.hello.get()
  return { message: res.data?.message ?? "" }
}

// The route file co-locates loader/meta → not a Fast Refresh boundary. The view lives in <Counter>.
export default function Home(props: { data: LoaderData<typeof loader> }) {
  return <Counter message={props.data.message} />
}

// examples/hmr-svelte/routes/index.svelte
<!--
  Home route. `<script module>` exports loader/meta (server-only — tree-shaken from the client); the
  instance `<script>` + markup are the component. The view lives in <Counter> so editing it
  hot-swaps with state intact; this route file full-reloads on save (it exports loader/meta).
-->
<script module>
  export const meta = {
    title: "nifra — HMR (Svelte)",
    meta: [{ name: "description", content: "True HMR via @nifrajs/web/vite" }],
  }

  // Proves SSR still runs under the Vite dev server: this value is server-rendered into the document.
  export async function loader({ api }) {
    const res = await api.hello.get()
    return { message: res.data?.message ?? "" }
  }
</script>

<script>
  import Counter from "../components/Counter.svelte"

  let { data } = $props()
</script>

<Counter message={data.message} />
