// packages/web-solid/src/await.ts
import type { Deferred } from "@nifrajs/web"
/**
 * `@nifrajs/web-solid/await` - the `<Await>` primitive for deferred loader data (`defer()`). Isomorphic
 * and imports only `solid-js` + a type from `@nifrajs/web` (never `solid-js/web`'s server or the Babel
 * plugin), so route components can use it without dragging server/build code into the client bundle.
 * No JSX (the package builds with plain `tsc`).
 *
 * Solid streams the boundary natively: on the server `createResource` awaits the deferred promise,
 * `<Suspense>` flushes the fallback then the resolved content mid-stream, and Solid serializes the
 * resource value into its hydration data - so the client hydrates the streamed content without a
 * re-fetch (it reads `_$HY`, not the registry promise).
 */
import { createComponent, createResource, type JSX, Suspense } from "solid-js"

export interface AwaitProps<T> {
  /** A `Deferred<T>` from a loader's `defer(...)`, or an already-resolved value (client nav). */
  readonly resolve: Deferred<T> | T
  readonly fallback?: JSX.Element
  /** Rendered if the deferred rejects. Without it the error propagates to the nearest
   * `<ErrorBoundary>`. */
  readonly errorFallback?: (error: unknown) => JSX.Element
  readonly children: (value: T) => JSX.Element
}

function isDeferred<T>(value: Deferred<T> | T): value is Deferred<T> {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as { __nifra_deferred?: unknown }).__nifra_deferred === true
  )
}

/**
 * Render deferred loader data: show `fallback` until the `Deferred` settles (streamed in by the
 * server), then `children(value)`. An already-resolved `resolve` (a client navigation awaited it)
 * renders immediately. Pairs with a loader's `defer(...)`.
 */
export function Await<T>(props: AwaitProps<T>): JSX.Element {
  if (!isDeferred(props.resolve)) return props.children(props.resolve)
  const marker = props.resolve
  const [data] = createResource(() => marker.promise)
  return createComponent(Suspense, {
    get fallback() {
      return props.fallback
    },
    get children() {
      // Errored? Render `errorFallback`, else rethrow to an outer <ErrorBoundary>. Check `data.error`
      // BEFORE `data()` (which would rethrow). Otherwise: `data()` suspends until the resource
      // settles (on the client Solid reads the serialized value - no re-fetch).
      if (data.error !== undefined) {
        if (props.errorFallback) return props.errorFallback(data.error)
        throw data.error
      }
      const value = data()
      return value === undefined ? null : props.children(value)
    },
  })
}

// packages/web-svelte/src/Await.svelte
<!--
  Await.svelte — the `<Await>` primitive for deferred loader/action data (`defer()`), built on Svelte's
  native `{#await}` block + scoped-snippet props: `children(value)` (resolved), `pending`, `error(err)`.

  Svelte SSR renders the PENDING branch of `{#await}` (it does not block on the promise), so the server
  emits the fallback and the client resolves it (hydration / soft-nav) — matching nifra's non-blocking
  `defer()` (like the Vue adapter; contrast React/Preact, which stream the resolved content into the SSR
  HTML). An already-resolved `resolve` (a plain value, or a client nav that awaited it) renders directly.
  Plain-JS script (no TS) so it needs no svelte TS preprocessor.
-->
<script>
  let { resolve, children, pending, error } = $props()
  const isDeferred = (v) =>
    v != null && typeof v === "object" && v.__nifra_deferred === true
</script>

{#if isDeferred(resolve)}
  {#await resolve.promise}
    {@render pending?.()}
  {:then value}
    {@render children?.(value)}
  {:catch err}
    {@render error?.(err)}
  {/await}
{:else}
  {@render children?.(resolve)}
{/if}
