// bench/ssr/nifra-svelte-static/routes/index.svelte
<script lang="ts" module>
  import { catalogItems, type CatalogPageData } from "../../shared/catalog.ts"

  export const meta = { title: "nifra SSR bench (Svelte SSG)" }
  export const prerender = true

  export function loader(): CatalogPageData {
    return { items: catalogItems() }
  }
</script>

<script lang="ts">
  import App from "../../nifra-svelte/App.svelte"
  import type { LoaderData } from "@nifrajs/client"

  let { data }: { data: LoaderData<typeof loader> } = $props()
</script>

<App {data} />

// bench/ssr/nifra-static/routes/index.tsx
import type { LoaderData } from "@nifrajs/client"
import { App } from "../../nifra/app.tsx"
import { type CatalogPageData, catalogItems } from "../../shared/catalog.ts"

export const meta = { title: "nifra SSR bench (SSG)" }

export const prerender = true

export function loader(): CatalogPageData {
  return { items: catalogItems() }
}

export default function Index(props: { data: LoaderData<typeof loader> }) {
  return <App data={props.data} />
}
