// packages/web-svelte/src/Content.svelte
<!--
  Content.svelte - render trusted pre-rendered HTML (e.g. a @nifrajs/content collection entry's `.html`)
  into the DOM via Svelte's {@html}. Pairs with content collections: <Content html={entry.html} />.
  `as` picks the wrapper element; extra attributes in `...rest` (class/style/id/data-*) pass through.

  Security: {@html} injects raw HTML, so `html` MUST be trusted (your own Markdown/content, rendered at
  build/server time) - never pass user-supplied HTML without sanitizing it first. Plain-JS script.
-->
<script>
  /** @type {{ html: import('@nifrajs/web').TrustedHtml, as?: string, [key: string]: unknown }} */
  let { html, as = "div", ...rest } = $props()
</script>

<svelte:element this={as} {...rest}>{@html html}</svelte:element>

// packages/web-solid/src/content.ts
/**
 * `@nifrajs/web-solid/content` - render pre-rendered HTML (e.g. a `@nifrajs/content` collection entry's
 * `.html`) into the DOM. Solid sets `innerHTML` reactively on a `<Dynamic>` element. Pairs with content
 * collections: `<Content html={entry.html} />`. No JSX (`createComponent`/`Dynamic`), so it builds with
 * plain `tsc`.
 *
 * Security: injects raw HTML, so `html` MUST be trusted (your own Markdown/content, rendered at
 * build/server time) - never pass user-supplied HTML without sanitizing it first.
 */

import type { TrustedHtml } from "@nifrajs/web"
import { createComponent, type JSX, mergeProps, splitProps } from "solid-js"
import { Dynamic } from "solid-js/web"

export interface ContentProps {
  /** Trusted, pre-rendered HTML (e.g. `entry.html`). */
  readonly html: TrustedHtml
  /** Wrapper element (default `"div"`). */
  readonly as?: string
  /** DOM passthrough (`class`, `style`, `id`, `data-*`, handlers). */
  readonly [key: string]: unknown
}

/** Render trusted HTML into a wrapper element. Extra props pass through reactively. */
export function Content(props: ContentProps): JSX.Element {
  const [, rest] = splitProps(props, ["html", "as"])
  // A function source keeps `component`/`innerHTML` reactive (matches the `<Image>` pattern).
  return createComponent(
    Dynamic,
    mergeProps(rest, () => ({ component: props.as ?? "div", innerHTML: props.html })),
  )
}
