// examples/web-solid/app.tsx
import { createSignal } from "solid-js"

export interface PageData {
  message: string
  start: number
}

/** A route component - `data` is the (typed) loader output. The signal proves hydration. */
export function App(props: { data: PageData }) {
  const [count, setCount] = createSignal(props.data.start)
  return (
    <main>
      <h1>{props.data.message}</h1>
      <button id="btn" type="button" onClick={() => setCount(count() + 1)}>
        count: {count()}
      </button>
    </main>
  )
}

// examples/web-react/app.tsx
import { useState } from "react"

export interface PageData {
  message: string
  start: number
}

/** A React route component - `data` is the (typed) loader output. The state proves hydration. */
export function App(props: { data: PageData }) {
  const [count, setCount] = useState(props.data.start)
  return (
    <main>
      <h1>{props.data.message}</h1>
      <button id="btn" type="button" onClick={() => setCount((c) => c + 1)}>
        count: {count}
      </button>
    </main>
  )
}
