// packages/web-solid/src/client.ts
import type { MountRouterOptions, RenderProps } from "@nifrajs/web"
// `/client`, not the root: the root's graph carries the server, and Vite's dev server evaluates it
// instead of tree-shaking it - which broke hydration before the browser ran a line of app code.
import { searchOfChain } from "@nifrajs/web/client"
/**
 * @nifrajs/web-solid/client - Solid client runtime. `hydrate` hydrates a single SSR'd route;
 * `mountRouter` hydrates the initial route then drives navigation through a Solid signal - so a
 * same-route update (revalidation, a param change, an optimistic submit) updates **in place** via
 * fine-grained reactivity, preserving the layout chain + focus + scroll. Runs against Solid's client
 * build; kept in its own entry so SSR code never ships to the client bundle. No JSX - Solid's package
 * build is plain `tsc`, so this uses Solid's runtime functions directly, like `compose`.
 */
import { createSignal } from "solid-js"
import { hydrate as solidHydrate, render as solidRender } from "solid-js/web"
import { compose } from "./compose.ts"
import { setMountedRouter } from "./fetcher.ts"

// The `_error` boundary chain element - defined in its own module, re-exported here so nifra's client
// codegen resolves it from `@nifrajs/web-solid/client` alongside `mountRouter`.
export { errorBoundary } from "./error.ts"

/** Hydrate a server-rendered Solid layout `chain` (with the loader `props`) inside `container`. */
export function hydrate(chain: readonly unknown[], props: RenderProps, container: unknown): void {
  solidHydrate(compose(chain, props), container as Element)
}

/**
 * Mount a Solid Router driven by the agnostic store. The first render *hydrates* the SSR'd chain. The
 * route's props are exposed as **getters over a signal** created inside the render root, so:
 *
 * - **Same route** (revalidation, a param change, an optimistic submit) - the snapshot signal is
 *   updated and only the components reading the changed props re-run; the layout chain stays mounted,
 *   so **focus and scroll are preserved**. This is the case the old "dispose + re-render on every
 *   navigation" implementation regressed.
 * - **Different route** - the matched chain genuinely changed (different page + layouts), so the root
 *   is disposed and the new chain is rendered. (Getter-props are a transparent reactive boundary, so
 *   they don't shift Solid's structural hydration keys - unlike a `<Show>`, which would.)
 */
export function mountRouter(options: MountRouterOptions): void {
  const { router, routes, searchSchemas, container } = options
  setMountedRouter(router) // expose it to createFetcher/useFetchers (same page, client-only)
  const el = container as Element

  let dispose: (() => void) | undefined
  let mountedRouteId: string | null = null
  // The setter for the currently-mounted route's reactive props - same-route settles push through it.
  let update: ((snapshot: ReturnType<typeof router.snapshot>) => void) | null = null

  const mount = (first: boolean): void => {
    const initial = router.snapshot()
    mountedRouteId = initial.routeId
    const renderer = first ? solidHydrate : solidRender
    dispose = renderer(() => {
      // Signal owned by THIS render root (so it's never ownerless). `props` are getters over it; a
      // same-route settle calls `update(snapshot)` and the reading components update in place - no
      // recompose, so the layout chain + focus + scroll survive. Cast bridges
      // `exactOptionalPropertyTypes` (a getter is always present, returning `undefined` when idle -
      // the documented "absent on idle" semantics for `submission`).
      const [snapshot, setSnapshot] = createSignal(initial)
      update = setSnapshot
      const props = {
        get data() {
          return snapshot().data
        },
        get actionData() {
          return snapshot().actionData
        },
        get pending() {
          return snapshot().pending
        },
        get search() {
          // The SAME searchOfChain the server ran, over this snapshot's URL - a same-route search change
          // updates in place (fine-grained), matching the SSR value on hydration.
          const s = snapshot()
          const idx = s.path.indexOf("?")
          return searchOfChain(
            searchSchemas?.[s.routeId] ?? [],
            idx === -1 ? "" : s.path.slice(idx),
          )
        },
        get submission() {
          return snapshot().submission
        },
      } as RenderProps
      // The matched chain is fixed for this mount (routeId is constant here); a route *change* disposes
      // and re-mounts below, so the root render fn reads no signal and never re-runs on its own.
      return compose(routes[initial.routeId] ?? [], props)()
    }, el)
  }

  mount(true)
  router.subscribe(() => {
    const snapshot = router.snapshot()
    if (snapshot.pending) return // skip the in-flight tick; act once settled
    if (snapshot.routeId === mountedRouteId) {
      update?.(snapshot) // same route → reactive in-place update (preserves layout/focus/scroll)
    } else {
      dispose?.() // route changed → tear down and render the new chain
      mount(false)
    }
  })
}

// packages/web-react/src/client.ts
import type { MountRouterOptions, RenderProps } from "@nifrajs/web"
// `/client`, not the root: the root's graph carries the server, and Vite's dev server evaluates it
// instead of tree-shaking it - which broke hydration before the browser ran a line of app code.
import { searchOfChain } from "@nifrajs/web/client"
/**
 * @nifrajs/web-react/client - React client runtime. `hydrate` hydrates a single SSR'd route;
 * `mountRouter` hydrates a stateful Router that subscribes to the agnostic store (via
 * `useSyncExternalStore`) and re-renders the matched chain on every client navigation (no full
 * reload). Kept in its own entry so server code stays out of the client bundle.
 */
import { createElement, type FunctionComponent, useSyncExternalStore } from "react"
import { hydrateRoot } from "react-dom/client"
import { compose } from "./compose.ts"
import { setMountedRouter } from "./fetcher.ts"

// The `_error` boundary chain element - defined in its own (react-dom-free) module, re-exported here so
// nifra's client codegen resolves it from `@nifrajs/web-react/client` alongside `mountRouter`.
export { errorBoundary } from "./error.ts"

/** Hydrate a server-rendered React layout `chain` (with the loader `props`) inside `container`. */
export function hydrate(chain: readonly unknown[], props: RenderProps, container: unknown): void {
  hydrateRoot(container as Element, compose(chain, props))
}

/**
 * Hydrate a stateful React Router. `useSyncExternalStore` subscribes to the agnostic store and
 * re-renders the matched layout chain on each store change - so client navigations swap routes
 * without a full reload. `getServerSnapshot` (3rd arg) returns the initial state, matching the
 * SSR markup on hydration.
 */
export function mountRouter(options: MountRouterOptions): void {
  const { router, routes, searchSchemas, container } = options
  setMountedRouter(router) // expose it to useFetcher/useFetchers (same page, client-only)
  const Router: FunctionComponent = () => {
    const state = useSyncExternalStore(router.subscribe, router.snapshot, router.snapshot)
    // Derive this route's typed `search` from the URL query + the route's schema CHAIN (layout schemas +
    // page, merged page-wins), the SAME `searchOfChain` the server ran, so `useSearch` reads an identical
    // value and hydrates with no drift.
    const q = state.path.indexOf("?")
    const rawSearch = q === -1 ? "" : state.path.slice(q)
    return compose(routes[state.routeId] ?? [], {
      data: state.data,
      actionData: state.actionData,
      pending: state.pending,
      ...(state.pendingPath !== undefined ? { pendingPath: state.pendingPath } : {}),
      // `params`/`path` feed the routing hooks (useParams/useLocation) via compose's RouterContext -
      // sourced from router state here, matching the SSR render's request-derived values on hydration.
      params: state.params,
      path: state.path,
      search: searchOfChain(searchSchemas?.[state.routeId] ?? [], rawSearch),
      // The in-flight submission (for optimistic UI) - spread only when present.
      ...(state.submission ? { submission: state.submission } : {}),
    })
  }
  hydrateRoot(container as Element, createElement(Router))
}
