// packages/web-svelte/src/Content.svelte
<!--
  Content.svelte — render trusted pre-rendered HTML (e.g. a @nifrajs/content collection entry's `.html`)
  into the DOM via Svelte's {@html}. Pairs with content collections: <Content html={entry.html} />.
  `as` picks the wrapper element; extra attributes in `...rest` (class/style/id/data-*) pass through.

  Security: {@html} injects raw HTML, so `html` MUST be trusted (your own Markdown/content, rendered at
  build/server time) — never pass user-supplied HTML without sanitizing it first. Plain-JS script.
-->
<script>
  let { html, as = "div", ...rest } = $props()
</script>

<svelte:element this={as} {...rest}>{@html html}</svelte:element>

// packages/web-react/src/content.ts
/**
 * `@nifrajs/web-react/content` - render pre-rendered HTML (e.g. a `@nifrajs/content` collection entry's
 * `.html`, or any Markdown→HTML string) into the DOM via `dangerouslySetInnerHTML`. Pairs with content
 * collections: `<Content html={entry.html} />`.
 *
 * Security: this injects raw HTML, so the `html` MUST be trusted (your own Markdown/content, rendered
 * at build/server time) - never pass user-supplied HTML without sanitizing it first.
 */
import {
  type ComponentPropsWithoutRef,
  createElement,
  type ElementType,
  type ReactElement,
} from "react"

export interface ContentProps
  extends Omit<ComponentPropsWithoutRef<"div">, "dangerouslySetInnerHTML" | "children"> {
  /** Trusted, pre-rendered HTML (e.g. `entry.html`). */
  readonly html: string
  /** Wrapper element (default `"div"`). */
  readonly as?: ElementType
}

/** Render trusted HTML into a wrapper element. Extra props (`className`, `id`, `style`, …) pass through. */
export function Content({ html, as, ...rest }: ContentProps): ReactElement {
  return createElement(as ?? "div", { ...rest, dangerouslySetInnerHTML: { __html: html } })
}
