// packages/web-solid/src/fetcher.ts
import type { ClientRouter, Fetcher, FetcherState } from "@nifrajs/web"
import {
  createMountedRouterRef,
  IDLE_FETCHER_STATE,
  noopAsync,
} from "@nifrajs/web/internal/fetcher-runtime"
/**
 * `@nifrajs/web-solid/fetcher` - Solid bindings for concurrent fetchers. `createFetcher(key)` bridges an
 * independent {@link Fetcher}'s `subscribe`/`snapshot` store into a Solid signal (the pattern the F16
 * spike confirmed) and returns its reactive state accessor plus `load`/`submit`; `useFetchers()`
 * bridges the whole live collection. Imports only `solid-js` (never `solid-js/web`), so route
 * components can use it on the server *and* client without pulling server/build code into the wrong
 * bundle. No JSX (the package builds with plain `tsc`).
 *
 * The router that owns the fetchers registers itself via `setMountedRouter` from `mountRouter`. On the
 * server (no mount) the accessors return an idle state - fetchers are client-only - so SSR markup is
 * unchanged and the first client render after `mountRouter` takes over cleanly.
 */
import { type Accessor, createSignal, onCleanup } from "solid-js"

const mountedRouter = createMountedRouterRef()

/** Register (or clear) the router that owns fetchers - called by `mountRouter`. Not for app use. */
export function setMountedRouter(router: ClientRouter | undefined): void {
  mountedRouter.set(router)
}

/** A fetcher's reactive state accessor plus its imperative `load`/`submit`. */
export interface FetcherHandle {
  /** Reactive accessor for the fetcher's {@link FetcherState} (`pending`/`data`/`actionData`/...). */
  readonly state: Accessor<FetcherState>
  /** Load a route path's loader data into this fetcher (concurrent; doesn't touch the active view). */
  readonly load: (path: string) => Promise<void>
  /** Submit an action into this fetcher (concurrent); honors `X-Nifra-Revalidate`. */
  readonly submit: (action: string, body: NonNullable<RequestInit["body"]>) => Promise<void>
}

/**
 * Bind the independent fetcher for `key` (created lazily, stable). Returns a reactive `state()`
 * accessor + `load`/`submit`. Multiple `createFetcher` calls with different keys run concurrently
 * without disturbing the active route or each other. Call inside a component (owns the subscription).
 */
export function createFetcher(key: string): FetcherHandle {
  const fetcher = mountedRouter.get()?.fetcher(key)
  const [state, setState] = createSignal<FetcherState>(
    fetcher ? fetcher.snapshot() : IDLE_FETCHER_STATE,
  )
  if (fetcher !== undefined) {
    onCleanup(fetcher.subscribe(() => setState(fetcher.snapshot())))
    return { state, load: fetcher.load, submit: fetcher.submit }
  }
  return { state, load: noopAsync, submit: noopAsync }
}

/**
 * Bind the whole live fetcher collection - for a global busy view. Returns a reactive accessor; read
 * each entry's `.snapshot()` for its state. Updates whenever any fetcher transitions or one is created.
 */
export function useFetchers(): Accessor<readonly Fetcher[]> {
  const router = mountedRouter.get()
  const [list, setList] = createSignal<readonly Fetcher[]>(router ? router.fetchers() : [])
  if (router !== undefined) {
    onCleanup(router.subscribeFetchers(() => setList(router.fetchers())))
  }
  return list
}

// packages/web-react/src/fetcher.ts
import type { ClientRouter, Fetcher, FetcherState } from "@nifrajs/web"
import {
  createMountedRouterRef,
  IDLE_FETCHER_STATE,
  idleFetcherSnapshot,
  noFetchers,
  noopAsync,
  noopSubscribe,
} from "@nifrajs/web/internal/fetcher-runtime"
/**
 * `@nifrajs/web-react/fetcher` - React bindings for concurrent fetchers. `useFetcher(key)` subscribes a
 * component to an independent {@link Fetcher} (via `useSyncExternalStore`) and returns its reactive
 * state plus `load`/`submit`; `useFetchers()` subscribes to the whole live collection. Imports only
 * `react` (never `react-dom/*`), so route components can use it on the server *and* client without
 * dragging either DOM build into the wrong bundle. No JSX (the package builds with plain `tsc`).
 *
 * The router that owns the fetchers is the one `mountRouter` hydrated - it registers itself here via
 * `setMountedRouter`. On the server (no mount) there is no router, so the hooks return an idle state
 * (fetchers are client-only); the first client render after `mountRouter` sees the real fetcher, so
 * there's no hydration mismatch.
 */
import { useSyncExternalStore } from "react"

const mountedRouter = createMountedRouterRef()

/** Register (or clear) the router that owns fetchers - called by `mountRouter`. Not for app use. */
export function setMountedRouter(router: ClientRouter | undefined): void {
  mountedRouter.set(router)
}

// Stable idle values for the server / pre-mount snapshot (stable refs → no `useSyncExternalStore`
// loop, no hydration mismatch).

/** A fetcher's reactive {@link FetcherState} plus its imperative `load`/`submit`. */
export interface FetcherHandle extends FetcherState {
  /** Load a route path's loader data into this fetcher (concurrent; doesn't touch the active view). */
  readonly load: (path: string) => Promise<void>
  /** Submit an action into this fetcher (concurrent); honors `X-Nifra-Revalidate`. */
  readonly submit: (action: string, body: NonNullable<RequestInit["body"]>) => Promise<void>
}

/**
 * Subscribe to the independent fetcher for `key` (created lazily, stable across renders). Returns its
 * state (`pending`/`data`/`actionData`/`submission`) + `load`/`submit`. Multiple `useFetcher` calls
 * with different keys run concurrently without disturbing the active route or each other.
 */
export function useFetcher(key: string): FetcherHandle {
  const fetcher = mountedRouter.get()?.fetcher(key)
  const state = useSyncExternalStore(
    fetcher?.subscribe ?? noopSubscribe,
    fetcher?.snapshot ?? idleFetcherSnapshot,
    () => IDLE_FETCHER_STATE, // server: fetchers are client-only → idle (matches the first client render)
  )
  return { ...state, load: fetcher?.load ?? noopAsync, submit: fetcher?.submit ?? noopAsync }
}

/**
 * Subscribe to the whole live fetcher collection - for a global busy view (e.g. "3 saving…"). Read
 * each entry's `.snapshot()` for its state. Re-renders whenever any fetcher transitions or a new one
 * is created.
 */
export function useFetchers(): readonly Fetcher[] {
  const router = mountedRouter.get()
  return useSyncExternalStore(
    router?.subscribeFetchers ?? noopSubscribe,
    router?.fetchers ?? noFetchers,
    noFetchers,
  )
}
