// bench/ssr/preact-ssr/src/app.tsx
import { h, type VNode } from "preact"

export interface PageData {
  readonly items: ReadonlyArray<{ readonly id: number; readonly name: string }>
}

export function App(props: { data: PageData }): VNode {
  return h(
    "main",
    null,
    h("h1", null, `Items (${props.data.items.length})`),
    h(
      "ul",
      null,
      props.data.items.map((it) => h("li", { key: it.id }, it.name)),
    ),
  )
}

// bench/ssr/nifra-solid/app.tsx
import { For } from "solid-js"
import type { CatalogPageData } from "../shared/catalog.ts"

export function App(props: { data: CatalogPageData }) {
  return (
    <main>
      <h1>Items ({props.data.items.length})</h1>
      <ul>
        <For each={props.data.items}>{(it) => <li>{it.name}</li>}</For>
      </ul>
    </main>
  )
}
