// examples/routing-preact/routes/_layout.tsx
/** @jsxImportSource preact */
import type { ComponentChildren } from "preact"

/** Root layout — wraps every page; the nav proves the layout renders + client nav works on Preact. */
export default function Layout(props: { children?: ComponentChildren }) {
  return (
    <div>
      <nav id="nav">
        <a href="/">home</a> · <a href="/todos">todos</a>
      </nav>
      {props.children}
    </div>
  )
}

// examples/routing-vue/routes/_layout.tsx
import { defineComponent, h } from "vue"

// Root layout — wraps every page via its default slot (compose passes the child there); the nav
// proves the layout renders + client nav works on Vue. Render function (h), no JSX/SFC compiler.
export default defineComponent({
  name: "Layout",
  setup(_props, { slots }) {
    return () =>
      h("div", null, [
        h("nav", { id: "nav" }, [
          h("a", { href: "/" }, "home"),
          " · ",
          h("a", { href: "/todos" }, "todos"),
        ]),
        slots.default?.(),
      ])
  },
})
