// examples/routing-vue-sfc/routes/_layout.vue
<!-- Root layout — renders the page via the default slot; the nav proves client navigation works.
     compose() passes layouts a `null` props bag, so no defineProps here. -->
<template>
  <div>
    <nav id="nav"><a href="/">home</a> · <a href="/about">about</a></nav>
    <slot />
  </div>
</template>

// examples/routing-preact/routes/_layout.tsx
/** @jsxImportSource preact */
import type { ComponentChildren } from "preact"

/** Root layout — wraps every page; the nav proves the layout renders + client nav works on Preact. */
export default function Layout(props: { children?: ComponentChildren }) {
  return (
    <div>
      <nav id="nav">
        <a href="/">home</a> · <a href="/todos">todos</a>
      </nav>
      {props.children}
    </div>
  )
}
