// packages/create-nifra/template-site/routes/_404.tsx
import Layout from "./_layout"

export const meta = { title: "Not found" }

// nifra's catch-all renders _404 without the layout chain, so it wraps itself in the root Layout.
export default function NotFound() {
  return (
    <Layout>
      <section className="hero">
        <h1>
          <span className="grad">404</span>
        </h1>
        <p>That page doesn't exist.</p>
        <a className="btn" href="/">
          ← Back home
        </a>
      </section>
    </Layout>
  )
}

// packages/create-nifra/template-site-vue/routes/_404.vue
<!-- nifra's catch-all renders _404 WITHOUT the layout chain, so it wraps itself in the root Layout. -->
<script lang="ts">
export const meta = { title: "Not found" }
</script>

<script setup lang="ts">
import Layout from "./_layout.vue"
</script>

<template>
  <Layout>
    <section class="hero">
      <h1><span class="grad">404</span></h1>
      <p>That page doesn't exist.</p>
      <a class="btn" href="/">← Back home</a>
    </section>
  </Layout>
</template>
